#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server:

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi


file="$1"
key="$4"
user="$3"
host="$2"


scp -i "$key" -o StrictHostKeyChecking=no "$file" "$user@$host:~/"
