#!/usr/bin/env bash
# Install nginx on your web-01 server 52.91.148.97

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx starti
