#!/usr/bin/env bash
#read field 1 and field 9 of Apache log file
log_file="apache-access.log"

# Use awk to extract the IP address and HTTP status code from the log file
awk '{print $1, $9}' "$log_file"
