#!/usr/bin/env bash
# Display "Best School" 10 times and displays "Hi" for the 9th iteration
i=1
while ((i<=10)); do
	if [ $i == 9 ]
	then
		echo "Best School"
		echo "Hi"
		((i++));
		continue
	fi
		 echo "Best School"
	((i++));
done
