#!/usr/bin/env bash
# Displays hours from 0 to 12 and minutes from 1 to 59
i=0
while ((i<=12)); do
	j=1
	while ((j<=59)); do
		case "$j" in
			1)
				echo "Hour: $i"
				echo "1";;
			*)
				echo "$j"
		esac
		((j++));
	done
	((i++))
done
