#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash. 
LIST="$(ls -1)"
for i in $LIST; do
    echo "$i" | cut -d'-' -f2
done
