#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash. 
for file in *-*; do
	part_after_dash="${file#*-}"
	echo "$part_after_dash"
done
