#!/usr/bin/env bash
#test if file exist or empty

file_path="$1"  # Replace this with the actual path to your school file

if [ -e "$file_path" ]; then
    echo "school file exists"
    
    if [ -s "$file_path" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    
    if [ -f "$file_path" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
